[package]
name = "rust-first-api"
version = "0.1.0"
edition = "2021"

[dependencies]
postgrest = "1.5.0"
dotenv = "0.15.0"
serde = { version = "1.0.152", features = ["derive"] }
rocket = { version = "0.5.0-rc.2", features = ["json"] }
uuid = { version = "1.3.0", features = ["v4"] }